### ISSUE TITLE
AttributeError: module 'azure.functions._abc' has no attribute 'SqlRow' Stack

### ISSUE THREAD

**Issue by hbensalem** [Azure/azure-functions-python-worker#1029]
One of our functions used to work fine for the last weeks and still works properly locally but on azure we get the following error. we tried redeploying our code on a completely new function and we still see the same issue:

Result: Failure Exception: AttributeError: module 'azure.functions._abc' has no attribute 'SqlRow' Stack: File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 324, in _handle__function_load_request ExtensionManager.function_load_extension( File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 16, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 65, in function_load_extension sdk = cls._try_get_sdk_with_extension_enabled() File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 225, in _try_get_sdk_with_extension_enabled sdk = get_sdk_from_sys_path() File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/common.py", line 121, in get_sdk_from_sys_path module = importlib.import_module('azure.functions') File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1030, in _gcd_import File "<frozen importlib._bootstrap>", line 1007, in _find_and_load File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 680, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/functions/__init__.py", line 20, in <module> from ._sql import SqlRow, SqlRowList File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/functions/_sql.py", line 10, in <module> class SqlRow(_abc.SqlRow, collections.UserDict):

#### Investigative information

Please provide the following:

- Timestamp: 10/05/2022
- Function App version: 2
- Function App name: unzipandprocesskrcdiag
- Function name(s) (as appropriate): trigger_KRCDiagProcessing
- Invocation ID:
- Region: West Europe

**Comment by vrdmr** [comment]
Hi all - apologies for this issue.

This issue was resolved with the new 1.11.2 release and the SQL issue has been resolved.

@hbensalem 

> So many hours lost for this. We always get weird issues with functions that are almost impossible to debug

I truly apologize for this and we would strive to improve this - both reducing such mishaps and also debuggability.

**Comment by nagendramishr** [comment]
I am seeing the same issue still with 1.11.2  and 1.11.3b1   

Using 11.3.b1 because this is what the docs say:


	Microsoft.Azure.WebJobs.Host.FunctionInvocationException
Exception message	Exception while executing function: Functions.CreateItem <--- Result: Failure Exception: AttributeError: module 'azure.functions' has no attribute 'SqlRow' Stack: File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 315, in _handle__function_load_request func = loader.load_function( File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/loader.py", line 85, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1030, in _gcd_import File "<frozen importlib._bootstrap>", line 1007, in _find_and_load File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 680, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/home/site/wwwroot/CreateItem/__init__.py", line 6, in <module> def main(req: func.HttpRequest, todoItems: func.Out[func.SqlRow]) -> func.HttpResponse:

**Comment by jackgoodsonjarden** [comment]
Agree with @nagendramishr, was fine on 1.11.0 with the error appearing in 1.11.1 and persisting in 1.11.3

`Result: Failure Exception: AttributeError: module 'azure.functions._abc' has no attribute 'SqlRow' Stack: File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 324, in _handle__function_load_request ExtensionManager.function_load_extension( File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 16, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 65, in function_load_extension sdk = cls._try_get_sdk_with_extension_enabled() File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 225, in _try_get_sdk_with_extension_enabled sdk = get_sdk_from_sys_path() File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/common.py", line 121, in get_sdk_from_sys_path module = importlib.import_module('azure.functions') File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1030, in _gcd_import File "<frozen importlib._bootstrap>", line 1007, in _find_and_load File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 680, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 850, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/functions/__init__.py", line 20, in <module> from ._sql import SqlRow, SqlRowList File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/functions/_sql.py", line 10, in <module> class SqlRow(_abc.SqlRow, collections.UserDict):`

**Comment by nagendramishr** [comment]
Quick update for everyone, looks like the backend had not deployed to US East.. when I redeployed to Central US, I was able to get it to work.

**Comment by wmwilson87** [comment]
Just experienced this myself.  I was deploying w/ azure-functions version 1.11.3 (azure_functions-1.11.3-py3-none-any.whl) and re-deployed to version 1.11.2 (azure_functions-1.11.2-py3-none-any.whl) and seem to be getting past this random error.  It's kinda comforting (and kinda terrifying) knowing the big boys at Microsoft are pushing out mistakes to production.

**Comment by CoAct-Atif** [comment]
Faced the error just now. Function deployed in Australia East region. Downgrading azure-functions to 1.11.0 version worked. Thanks @paoloripamonti.

`azure-functions==1.11.0`

**Comment by nicowijayards** [comment]
I just hit the same problem even with a simple HttpTrigger Hello World sample. I was on 4.8.0.0 and I downgraded it to 3.11.0.0, it's working again now. Why is this so buggy?

Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.HttpTriggerNW
 ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
Exception: AttributeError: module 'azure.functions._abc' has no attribute 'SqlRow'
Stack:   File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 315, in _handle__function_load_request
    func = loader.load_function(
  File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call
    return func(*args, **kwargs)
  File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/loader.py", line 85, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/site/wwwroot/HttpTriggerNW/__init__.py", line 3, in <module>
    import azure.functions as func
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/functions/__init__.py", line 24, in <module>
    from ._sql import SqlRow, SqlRowList
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/functions/_sql.py", line 10, in <module>
    class SqlRow(_abc.SqlRow, collections.UserDict):

**Comment by vrdmr** [comment]
Hi @wmwilson87, @CoAct-Atif, @nicowijayards - Firstly - apologies for the issue. I am really sorry you hit this issue. This is a miss on our end and I take full responsibility of this.

We released the 4.9.0 Host Version, which contains the Python Worker with the correct fix to all the regions and had been baking this for some time. We want to release the new library version with the new fixes but haven't been able to do it as the issue is with 4.8.0 Host Version - it doesn't have [Dependency Isolation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#python_isolate_worker_dependencies-preview) feature turned on by default. In 4.9.0 it is on by default (we are updating the changes in the docs as well to reflect it).

/cc @gavin-aguiar @YunchuWang

**Comment by sbsar6** [comment]
Has something changed recently. Our azure function was running fine in November but now it errors out with no attribute SqlRowList if the version is set to azure-functions==1.11.0 and an error that Azure.functions has no attribute SqlRow if the version is set to azure-functions==1.13.0b1.

**Comment by Akprasanth** [comment]
> Has something changed recently. Our azure function was running fine in November but now it errors out with no attribute SqlRowList if the version is set to azure-functions==1.11.0 and an error that Azure.functions has no attribute SqlRow if the version is set to azure-functions==1.13.0b1.

+1

**Comment by YunchuWang** [comment]
@Akprasanth Hello, thanks for reporting, can you please share your function app name and details following this link https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately ?

**Comment by MariDjor** [comment]
facing the same:

[2022-12-21T20:56:31.406Z] Worker failed to load function: 'HttpTriggerReadSQL' with function id: 'd6cd23ae-aa22-4f17-934d-c310d4f22e0a'.
[2022-12-21T20:56:31.407Z] Result: Failure
Exception: AttributeError: module 'azure.functions' has no attribute 'SqlRowList'
Stack:   File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9\WINDOWS\X64\azure_functions_worker\dispatcher.py", line 365, in _handle__function_load_request
    func = loader.load_function(
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9\WINDOWS\X64\azure_functions_worker\utils\wrappers.py", line 44, in call
    return func(*args, **kwargs)
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9\WINDOWS\X64\azure_functions_worker\loader.py", line 134, in load_function
    mod = importlib.import_module(fullmodname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\dmarinkovic\OneDrive - Microsoft\Documents\CODE\Playground2\HttpTriggerReadSQL\__init__.py", line 5, in <module>
    def main(req: func.HttpRequest, todoItem: func.SqlRowList) -> func.HttpResponse:

**Comment by et-shell** [comment]
Facing issue with azure-functions 1.11.0, 1.11.3, 1.13.0 -- Cannot get it to work
[2023-04-04T21:37:00.006Z] Executing 'Functions.TimerTrigger1' (Reason='Timer fired at 2023-04-04T16:37:00.0061392-05:00', Id=868576be-b520-4151-89d3-59b79d83114b)
[2023-04-04T21:37:00.303Z] Executed 'Functions.TimerTrigger1' (Failed, Id=868576be-b520-4151-89d3-59b79d83114b, Duration=290ms)
[2023-04-04T21:37:00.306Z] System.Private.CoreLib: Exception while executing function: Functions.TimerTrigger1. System.Private.CoreLib: Result: Failure
Exception: AttributeError: module 'azure.functions' has no attribute 'SqlRowList'
Stack:   File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\dispatcher.py", line 365, in _handle__function_load_request
    func = loader.load_function(
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\utils\wrappers.py", line 44, in call
    return func(*args, **kwargs)
  File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\loader.py", line 134, in load_function
    mod = importlib.import_module(fullmodname)
  File "C:\Apps\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\boxes\TimerTrigger1\__init__.py", line 10, in <module>
    def main(mytimer: func.TimerRequest, articles: func.SqlRowList) -> None:

**Comment by vrdmr** [comment]
Can you please share the Coretools you are using?

> Facing issue with azure-functions 1.11.0, 1.11.3, 1.13.0 -- Cannot get it to work [2023-04-04T21:37:00.006Z] Executing 'Functions.TimerTrigger1' (Reason='Timer fired at 2023-04-04T16:37:00.0061392-05:00', Id=868576be-b520-4151-89d3-59b79d83114b) [2023-04-04T21:37:00.303Z] Executed 'Functions.TimerTrigger1' (Failed, Id=868576be-b520-4151-89d3-59b79d83114b, Duration=290ms) [2023-04-04T21:37:00.306Z] System.Private.CoreLib: Exception while executing function: Functions.TimerTrigger1. System.Private.CoreLib: Result: Failure Exception: AttributeError: module 'azure.functions' has no attribute 'SqlRowList' Stack: File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\dispatcher.py", line 365, in _handle__function_load_request func = loader.load_function( File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\utils\wrappers.py", line 44, in call return func(*args, **kwargs) File "C:\Program Files\Microsoft\Azure Functions Core Tools\workers\python\3.9/WINDOWS/X64\azure_functions_worker\loader.py", line 134, in load_function mod = importlib.import_module(fullmodname) File "C:\Apps\Python39\lib\importlib__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "C:\Users\boxes\TimerTrigger1__init__.py", line 10, in def main(mytimer: func.TimerRequest, articles: func.SqlRowList) -> None:

**Comment by et-shell** [comment]
Azure Functions Core Tools
Core Tools Version:       4.0.4915 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.14.0.19631

**Comment by vrdmr** [comment]
Could you please update the core tools and try again? And trying the latest version of the library as well?

<img width="433" alt="image" src="https://user-images.githubusercontent.com/1047040/229929919-ea688bad-1129-4d3e-b6b7-c36f7bd2c589.png">

**Comment by et-shell** [comment]
@vrdmr - Thanks for the quick reply. I am specifying 'azure-functions==1.13.3' on my requirements.txt and I still get the same error. I cannot update my core tools right now, but II will try later. For some context, I am to query data from Azure SQL using bindings following [this example](https://github.com/dzsquared/sqlbindings-python-datatransfer/tree/main/SendDataToAPI).

**Comment by et-shell** [comment]
@vrdr -- I updated my Core Tools installation to version 4.0.5095 and specified 'azure-functions==1.13.3', the issue is resolved now. Thank you! 🤓
