### ISSUE TITLE
No module named 'azure.functions_worker'

### ISSUE THREAD

**Issue by tlaur** [Azure/azure-functions-python-worker#489]
I was trying to follow [these](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-python) instructions and have my python function app write to table storage, but if I include azure-cosmos in my requirements.txt, I get the following error when I try to run my function:

Exception has occurred: ModuleNotFoundError
No module named 'azure.functions_worker'
  File "c:\users\user\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 33, in main
    import azure.functions_worker
  File "c:\users\user\appdata\roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 46, in <module>
    main()

Issue similar to #151

**Comment by maiqbal11** [comment]
@ankitkumarr, I believe this is because we don't have an `__init__.py` currently packaged with the azure package in core tools dependencies?

**Comment by ankitkumarr** [comment]
@maiqbal11, yeah you are right!

@tlaur, this is on track to be fixed on the next release. As a work-around, you can delete `azure/__init__.py`. To find the location of that file, you can do this --
```python
$ python3.6
>>> import azure
>>> azure.__file__
```

This should not have any impact on your app.

**Comment by tlaur** [comment]
@ankitkumarr Thanks, removed .env/Include/Lib/azure/__init__.py from my virtual environment and the app runs fine now.

**Comment by asavaritayal** [comment]
This should be fixed in the latest Core Tools.

**Comment by equidevium** [comment]
Hello there. 

Apparently for me the error persists. 

I tried to install azure-functions-worker but it does not work even with that.

**Comment by nk-gears** [comment]
Same Issue for me.

**Comment by ankitkumarr** [comment]
Please open a separate issue if you saw similar errors. The root cause here was fixed and released. It is most likely a different cause and would need separate investigation.

cc: @Hazhzeng @maiqbal11

**Comment by Hazhzeng** [comment]
@tlaur @equidevium @nk-gears, this is due to the existing issues in 1.0.0b9 python worker. You can perform the following steps to mitigate the issues until [1.0.0b11 is released in the functions-core-tools](https://github.com/Azure/azure-functions-core-tools/pull/1474)

1. Go to C:\Users\<YourUserName>\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py
2. Change **azure.functions_worker** to **azure_functions_worker**
3. In your **requirements.txt**, add **azure_functions_worker**
4. Run **pip install -r requirements.txt**
​5. Run **func host start**
